
services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      APP_JWTSECRET: Xb34fJd9kPbvmJc84mDkV9b3Xb4fJd9kPbvmJc84mDkV9b3Xb34fJd9kPbvmJc84
      APP_JWTEXPIRATIONMS: 3600000  # 1 hour
    networks:
      - microservice-network

networks:
  microservice-network:
    external: true

