services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: Ab123456
      APP_JWTSECRET: Xb34fJd9kPbvmJc84mDkV9b3Xb4fJd9kPbvmJc84mDkV9b3Xb34fJd9kPbvmJc84
      APP_JWTEXPIRATIONMS: 3600000  # 1 hour
    depends_on:
      - redis
    networks:
      - microservice-network

  redis:
    image: redis:latest
    command: [ "redis-server", "--requirepass", "Ab123456" ]
    ports:
      - "6379:6379"
    networks:
      - microservice-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "Ab123456", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  microservice-network:
    external: true
