server:
  port: 8084  # Port for User Service

spring:
  profiles:
    active: default

# Default profile (local development and testing)
---
spring:
  config:
    activate:
      on-profile: default

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Logging level for the User Service
logging:
  level:
    com.jack.authservice: INFO

# SpringDoc settings for API documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# JWT settings specific to the Auth Service
app:
  jwtSecret: Xb34fJd9kPbvmJc84mDkV9b3Xb4fJd9kPbvmJc84mDkV9b3Xb34fJd9kPbvmJc84
  jwtExpirationMs: 3600000

security:
  authentication:
    enabled: false

# Docker profile (for running in containers)
---
spring:
  config:
    activate:
      on-profile: docker

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# Logging level for the User Service
logging:
  level:
    com.jack.authservice: INFO

# SpringDoc settings for API documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# JWT settings specific to the Auth Service
app:
  jwtSecret: Xb34fJd9kPbvmJc84mDkV9b3Xb4fJd9kPbvmJc84mDkV9b3Xb34fJd9kPbvmJc84
  jwtExpirationMs: 3600000

security:
  authentication:
    enabled: false  # Enable authentication as the User Service typically manages user authentication
